In [38]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import  train_test_split
import numpy as np
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import MinMaxScaler

In [39]:
df=pd.read_csv("/content/newdata.csv")

In [40]:
df

,Unnamed: 0,status,tld_in_path,tld_in_subdomain,url_length,subdomain_counts,is_https,has_redirects,count_suspicious_chars,is_ip_address,...,domain_age,num_digits,num_&,num_?,num_=,num_@,char_repit,num_digits_in_domain,num_dot_domain,num_hyphen_domain
0,0,1,0,0,37,1,0,0,7,0,...,-1,0,0,0,0,0,0,0,2,0
1,1,0,0,0,77,0,0,0,7,0,...,5767,17,0,0,0,0,0,0,1,0
2,2,0,0,1,126,3,1,-1,18,0,...,4004,19,2,1,3,0,0,0,4,1
3,3,1,0,0,18,1,0,1,5,0,...,-1,0,0,0,0,0,0,0,2,0
4,4,1,0,0,55,1,0,1,8,0,...,8175,0,0,0,0,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,11425,1,0,0,45,1,0,1,7,0,...,5396,0,0,0,0,0,0,0,2,0
11426,11426,0,1,0,84,1,0,1,15,0,...,6728,2,0,1,1,1,0,0,2,0
11427,11427,1,0,0,105,1,1,0,11,0,...,8515,15,0,1,1,0,0,0,2,0
11428,11428,1,0,0,38,1,0,1,6,0,...,2836,0,0,0,0,0,0,0,2,0
11429,11429,0,1,1,477,2,0,-1,99,1,...,-1,41,9,1,9,1,0,11,3,0

In [41]:
features = df.drop([ "status","Unnamed: 0",'char_repit'],axis = 1)
target = df['status']

1:legitimate
0:Phishing

In [42]:
features

,tld_in_path,tld_in_subdomain,url_length,subdomain_counts,is_https,has_redirects,count_suspicious_chars,is_ip_address,path_length,domain_age,num_digits,num_&,num_?,num_=,num_@,num_digits_in_domain,num_dot_domain,num_hyphen_domain
0,0,0,37,1,0,0,7,0,11,-1,0,0,0,0,0,0,2,0
1,0,0,77,0,0,0,7,0,47,5767,17,0,0,0,0,0,1,0
2,0,1,126,3,1,-1,18,0,20,4004,19,2,1,3,0,0,4,1
3,0,0,18,1,0,1,5,0,0,-1,0,0,0,0,0,0,2,0
4,0,0,55,1,0,1,8,0,33,8175,0,0,0,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,0,0,45,1,0,1,7,0,21,5396,0,0,0,0,0,0,2,0
11426,1,0,84,1,0,1,15,0,37,6728,2,0,1,1,1,0,2,0
11427,0,0,105,1,1,0,11,0,63,8515,15,0,1,1,0,0,2,0
11428,0,0,38,1,0,1,6,0,1,2836,0,0,0,0,0,0,2,0
11429,1,1,477,2,0,-1,99,1,10,-1,41,9,1,9,1,11,3,0

# **Normalize Features**

In [43]:
for column in features.columns:
    features[column] = (features[column] - features[column].min()) / (features[column].max() - features[column].min())

In [44]:
features

,tld_in_path,tld_in_subdomain,url_length,subdomain_counts,is_https,has_redirects,count_suspicious_chars,is_ip_address,path_length,domain_age,num_digits,num_&,num_?,num_=,num_@,num_digits_in_domain,num_dot_domain,num_hyphen_domain
0,0.0,0.0,0.015347,0.076923,0.0,0.5,0.028037,0.0,0.018272,0.000854,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.076923,0.000000
1,0.0,0.0,0.039902,0.000000,0.0,0.5,0.028037,0.0,0.078073,0.448471,0.025037,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000
2,0.0,1.0,0.069982,0.230769,1.0,0.0,0.130841,0.0,0.033223,0.311656,0.027982,0.105263,0.333333,0.157895,0.00,0.000000,0.230769,0.038462
3,0.0,0.0,0.003683,0.076923,0.0,1.0,0.009346,0.0,0.000000,0.000854,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.076923,0.000000
4,0.0,0.0,0.026397,0.076923,0.0,1.0,0.037383,0.0,0.054817,0.635341,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.076923,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,0.0,0.0,0.020258,0.076923,0.0,1.0,0.028037,0.0,0.034884,0.419680,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.076923,0.000000
11426,1.0,0.0,0.044199,0.076923,0.0,1.0,0.102804,0.0,0.061462,0.523048,0.002946,0.000000,0.333333,0.052632,0.25,0.000000,0.076923,0.000000
11427,0.0,0.0,0.057090,0.076923,1.0,0.5,0.065421,0.0,0.104651,0.661726,0.022091,0.000000,0.333333,0.052632,0.00,0.000000,0.076923,0.000000
11428,0.0,0.0,0.015961,0.076923,0.0,1.0,0.018692,0.0,0.001661,0.221015,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.076923,0.000000
11429,1.0,1.0,0.285451,0.153846,0.0,0.0,0.887850,1.0,0.016611,0.000854,0.060383,0.473684,0.333333,0.473684,0.25,0.229167,0.153846,0.000000

# Feature selection

In [45]:
num_feats=10

**Correlation**

In [46]:
def cor_selector(X, y,num_feats):
    cor_list = []
    feature_name = X.columns.tolist()
    # calculate the correlation with y for each feature
    for i in X.columns.tolist():
        cor = np.corrcoef(X[i], y)[0, 1]
        cor_list.append(cor)
    # replace NaN with 0
    cor_list = [0 if np.isnan(i) else i for i in cor_list]
    # feature name
    cor_feature = X.iloc[:,np.argsort(np.abs(cor_list))[-num_feats:]].columns.tolist()
    # feature selection? 0 for not select, 1 for select
    cor_support = [True if i in cor_feature else False for i in feature_name]
    return cor_support, cor_feature
cor_support, cor_feature = cor_selector(features, target,num_feats)

**Chi-Squared**

In [48]:
chi_selector = SelectKBest(chi2, k=num_feats)
chi_selector.fit(features, target)
chi_support = chi_selector.get_support()
chi_feature = features.loc[:,chi_support].columns.tolist()

**Recursive Feature Elimination**

In [50]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
rfe_selector = RFE(estimator=LogisticRegression(), n_features_to_select=num_feats, step=10, verbose=5)
rfe_selector.fit(features, target)
rfe_support = rfe_selector.get_support()
rfe_feature = features.loc[:,rfe_support].columns.tolist()

Fitting estimator with 18 features.

**Lasso**

In [57]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression

embeded_lr_selector = SelectFromModel(LogisticRegression(penalty="l1", solver="liblinear"), max_features=num_feats)
embeded_lr_selector.fit(features, target)
embeded_lr_support = embeded_lr_selector.get_support()
embeded_lr_feature = features.loc[:,embeded_lr_support].columns.tolist()

**random forest feature selection**

In [59]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

embeded_rf_selector = SelectFromModel(RandomForestClassifier(n_estimators=100), max_features=num_feats)
embeded_rf_selector.fit(features, target)
embeded_rf_support = embeded_rf_selector.get_support()
embeded_rf_feature = features.loc[:,embeded_rf_support].columns.tolist()

**LightGBM feature selection**

In [60]:
from sklearn.feature_selection import SelectFromModel
from lightgbm import LGBMClassifier

lgbc=LGBMClassifier(n_estimators=500, learning_rate=0.05, num_leaves=32, colsample_bytree=0.2,
            reg_alpha=3, reg_lambda=1, min_split_gain=0.01, min_child_weight=40)

embeded_lgb_selector = SelectFromModel(lgbc, max_features=num_feats)
embeded_lgb_selector.fit(features, target)

embeded_lgb_support = embeded_lgb_selector.get_support()
embeded_lgb_feature = features.loc[:,embeded_lgb_support].columns.tolist()

**view all selected features and choose best 15**

In [68]:
feature_selection_df = pd.DataFrame({'Feature':list(features), 'Pearson':cor_support, 'Chi-2':chi_support, 'RFE':rfe_support, 'Logistics':embeded_lr_support,
                                    'Random Forest':embeded_rf_support, 'LightGBM':embeded_lgb_support})
# count the selected times for each feature
feature_selection_df['Total'] = np.sum(feature_selection_df, axis=1)
# display the top 100
feature_selection_df = feature_selection_df.sort_values(['Total','Feature'] , ascending=False)
feature_selection_df.index = range(1, len(feature_selection_df)+1)

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return reduction(axis=axis, out=out, **passkwargs)

In [71]:
feature_selection_df

,Feature,Pearson,Chi-2,RFE,Logistics,Random Forest,LightGBM,Total
1,url_length,True,False,True,True,True,True,5
2,num_digits,True,False,True,True,True,True,5
3,domain_age,True,True,True,False,True,True,5
4,count_suspicious_chars,True,False,True,True,True,True,5
5,path_length,False,False,True,True,True,True,4
6,num_digits_in_domain,True,True,True,True,False,False,4
7,num_?,True,True,True,True,False,False,4
8,has_redirects,True,True,True,False,True,False,4
9,num_hyphen_domain,True,False,True,True,False,False,3
10,tld_in_subdomain,True,True,False,False,False,False,2
11,num_@,False,False,True,True,False,False,2
12,num_=,True,True,False,False,False,False,2
13,num_&,False,True,False,True,False,False,2
14,tld_in_path,False,True,False,False,False,False,1
15,subdomain_counts,False,False,False,True,False,False,1
16,is_ip_address,False,True,False,False,False,False,1
17,is_https,False,True,False,False,False,False,1
18,num_dot_domain,False,False,False,False,False,False,0

In [72]:
new_features=feature_selection_df.head(13)

In [76]:
new_features=features[new_features["Feature"]]

In [77]:
new_features

,url_length,num_digits,domain_age,count_suspicious_chars,path_length,num_digits_in_domain,num_?,has_redirects,num_hyphen_domain,tld_in_subdomain,num_@,num_=,num_&
0,0.015347,0.000000,0.000854,0.028037,0.018272,0.000000,0.000000,0.5,0.000000,0.0,0.00,0.000000,0.000000
1,0.039902,0.025037,0.448471,0.028037,0.078073,0.000000,0.000000,0.5,0.000000,0.0,0.00,0.000000,0.000000
2,0.069982,0.027982,0.311656,0.130841,0.033223,0.000000,0.333333,0.0,0.038462,1.0,0.00,0.157895,0.105263
3,0.003683,0.000000,0.000854,0.009346,0.000000,0.000000,0.000000,1.0,0.000000,0.0,0.00,0.000000,0.000000
4,0.026397,0.000000,0.635341,0.037383,0.054817,0.000000,0.000000,1.0,0.000000,0.0,0.00,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,0.020258,0.000000,0.419680,0.028037,0.034884,0.000000,0.000000,1.0,0.000000,0.0,0.00,0.000000,0.000000
11426,0.044199,0.002946,0.523048,0.102804,0.061462,0.000000,0.333333,1.0,0.000000,0.0,0.25,0.052632,0.000000
11427,0.057090,0.022091,0.661726,0.065421,0.104651,0.000000,0.333333,0.5,0.000000,0.0,0.00,0.052632,0.000000
11428,0.015961,0.000000,0.221015,0.018692,0.001661,0.000000,0.000000,1.0,0.000000,0.0,0.00,0.000000,0.000000
11429,0.285451,0.060383,0.000854,0.887850,0.016611,0.229167,0.333333,0.0,0.000000,1.0,0.25,0.473684,0.473684

# split data to train and test

In [78]:
X_train, X_test, y_train, y_test = train_test_split(new_features, target,test_size= 0.30,random_state =42)

# Random forest classifier

In [79]:
rf_param={
    'criterion': ['entropy', 'gini'],
}

In [80]:
rf_model=GridSearchCV(RandomForestClassifier(), rf_param)
rf_model.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['entropy', 'gini']})

In [81]:
rf_model.best_params_

{'criterion': 'gini'}

In [82]:
RF_prediction=rf_model.predict(X_test)

In [83]:
RF_prediction

array([1, 1, 1, ..., 0, 1, 0])

In [84]:
print(classification_report(y_test,RF_prediction))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88      1697
           1       0.88      0.89      0.89      1732

    accuracy                           0.89      3429
   macro avg       0.89      0.89      0.89      3429
weighted avg       0.89      0.89      0.89      3429

save model

In [85]:
import pickle

In [86]:
pickle.dump(rf_model, open("new_random_forest_model.sav", 'wb'))

# logistic regression

In [90]:
logistic_model = LogisticRegression(random_state=0,max_iter=1000).fit(X_train, y_train)

In [91]:
LR_prediction=logistic_model.predict(X_test)

In [92]:
print(classification_report(y_test,LR_prediction))

              precision    recall  f1-score   support

           0       0.78      0.70      0.74      1697
           1       0.73      0.81      0.77      1732

    accuracy                           0.75      3429
   macro avg       0.76      0.75      0.75      3429
weighted avg       0.76      0.75      0.75      3429

In [93]:
pickle.dump(logistic_model, open("new_logistic_regression_model.sav", 'wb'))

# Support vector classifier

In [94]:
from sklearn.svm import SVC

In [103]:
svc_param={
    'kernel': ['poly', 'rbf', 'sigmoid'],
    'gamma':['scale', 'auto']
}

In [104]:
svc_model=GridSearchCV(SVC(), svc_param)
svc_model.fit(X_train,y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'gamma': ['scale', 'auto'],
                         'kernel': ['poly', 'rbf', 'sigmoid']})

In [106]:
svc_model.best_params_

{'gamma': 'scale', 'kernel': 'rbf'}

In [107]:
svc_prediction=svc_model.predict(X_test)

In [108]:
print(classification_report(y_test,svc_prediction))

              precision    recall  f1-score   support

           0       0.87      0.63      0.73      1697
           1       0.71      0.91      0.80      1732

    accuracy                           0.77      3429
   macro avg       0.79      0.77      0.76      3429
weighted avg       0.79      0.77      0.76      3429

In [109]:
pickle.dump(svc_model, open("new_SVC_model.sav", 'wb'))